### ISSUE TITLE
'crypt.h' file not found

### ISSUE THREAD

**Issue by gu18168** [theimpostor/termux-vim-ycm#1]
python 3.6m/Python.h:39:10: fatal error: 'crypt.h' file not found

**Comment by theimpostor** [comment]
I think recent python changes caused this. Try installing libcrypt-dev.

**Comment by theimpostor** [comment]
Fixed with deca44949d40f80d5bd954bbb7d8176d68ca338b

**Comment by gu18168** [comment]
It can work, thank you
